# Generated by Django 3.1.6 on 2021-02-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(null=True, verbose_name='설명'),
        ),
    ]
